name: pe_teacher_app
description: "تطبيق أستاذ التربية البدنية"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - .env
    
